Models/ErrorViewModel.cs
namespace EfCoreApp.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

Controllers/CourseController.cs
using EfCoreApp.Data;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Internal;

namespace EfCoreApp.Controllers;

public class CourseController : Controller
{
    private readonly DataContext _context;

    public CourseController(DataContext context)
    {
        _context = context;
    }

    public async Task<IActionResult> Index()
    {
       var courses = await _context.Courses.ToListAsync();
       return View(courses);
    }

    public IActionResult Create()
    {
        return View();
    }
    
   [HttpPost]
   public async Task<IActionResult> Create(Course model)
   {
        _context.Courses.Add(model);
        await _context.SaveChangesAsync();
        return RedirectToAction("Index");
   }
    
   public async Task<IActionResult> Edit(int? id)
   {
        if(id == null)
        {
            return NotFound();
        }
        var course = await _context
        .Courses
        .Include(c => c.CourseRegistrations)
        .ThenInclude(c => c.Student)
        .FirstOrDefaultAsync(c => c.CourseId == id);
        if(course == null)
        {
            return NotFound();
        }
        return View(course);
   }

   [HttpPost]
   [ValidateAntiForgeryToken]
   public async Task<IActionResult> Edit(int? id,Course model)
   {
        if(id != model.CourseId)
        {
            return NotFound();
        }
        if(ModelState.IsValid)
        {
            try
            {
                _context.Update(model);
                await _context.SaveChangesAsync();
            }
            catch(DbUpdateConcurrencyException)
            {
                if(!_context.Courses.Any(c => c.CourseId == model.CourseId)) return NotFound();
                else throw;
            }
            return RedirectToAction("Index");
        }
        return View(model);
   }

   public async Task<IActionResult> Delete(int? id)
   {
        if(id == null)
        {
            return NotFound();
        }
        var course = await _context.Courses.FindAsync(id);
        if(course == null)
        {
            return NotFound();
        }
        return View(course);
   }

   [HttpPost]
   [ValidateAntiForgeryToken]
   public async Task<IActionResult> Delete([FromForm]int id)
   {
        var course = await _context.Courses.FindAsync(id);
        if(course == null)
        {
            return NotFound();
        }
        _context.Courses.Remove(course);
        await _context.SaveChangesAsync();
        return RedirectToAction("Index");
   }
}

Controllers/CourseRegisterController.cs
using EfCoreApp.Data;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

namespace EfCoreApp.Controllers;

public class CourseRegisterController : Controller
{
    private readonly DataContext _context;

    public CourseRegisterController(DataContext context)
    {
        _context = context;
    }

    public async Task<IActionResult> Index(){
        var registrations = await _context.CourseRegistrations.Include(x => x.Student)
                                                                .Include(x => x.Course).
                                                                ToListAsync();
        return View(registrations);
    }

    public async Task<IActionResult> Create()
    {
        ViewBag.Students = new SelectList(await _context.Students.ToListAsync(), "StudentId", "StudentNameSurname");
        ViewBag.Courses =  new SelectList(await _context.Courses.ToListAsync(), "CourseId", "CourseName");
        return View();
    }


    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Create(CourseRegistration model)
    {
        model.RegistrationDate = DateTime.Now;
        _context.CourseRegistrations.Add(model);
        await _context.SaveChangesAsync();
        return RedirectToAction("Index");
    }
}

Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using EfCoreApp.Models;

namespace EfCoreApp.Controllers;

public class HomeController : Controller
{
    public IActionResult Index()
    {
        return View();
    }

    public IActionResult Privacy()
    {
        return View();
    }
}

Controllers/StudentController.cs
using Microsoft.AspNetCore.Mvc;
using EfCoreApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
namespace EfCoreApp.Controllers;
public class StudentController : Controller
{
    private readonly DataContext _context;

    public StudentController(DataContext context)
    {
        _context = context;
    }
   public IActionResult Create()
   {
      return View();
   }
   public async Task<IActionResult> Index()
   {
      var students = await _context.Students.ToListAsync();
      return View(students);
   }

   [HttpPost]
   public async Task<IActionResult> Create(Student student)
   {
        _context.Students.Add(student);
        await _context.SaveChangesAsync();
        return RedirectToAction("Index");
   }

   public async Task<IActionResult> Edit(int? id)
   {
        if(id == null)
        {
            return NotFound();
        }
        var student = await _context
        .Students
        .Include(c => c.CourseRegistrations)
        .ThenInclude(c => c.Course)
        .FirstOrDefaultAsync(c => c.StudentId == id);

        if(student == null)
        {
            return NotFound();
        }
        return View(student);
   }

   [HttpPost]
   [ValidateAntiForgeryToken]
   public async Task<IActionResult> Edit(int? id,Student model)
   {
        if(id != model.StudentId)
        {
            return NotFound();
        }
        if(ModelState.IsValid)
        {
            try
            {
                _context.Update(model);
                await _context.SaveChangesAsync();
            }
            catch(DbUpdateConcurrencyException)
            {
                if(!_context.Students.Any(c => c.StudentId == model.StudentId)) return NotFound();
                else throw;
            }
            return RedirectToAction("Index");
        }
        return View(model);
   }

   public async Task<IActionResult> Delete(int? id)
   {
        if(id == null)
        {
            return NotFound();
        }
        var student = await _context.Students.FindAsync(id);
        if(student == null)
        {
            return NotFound();
        }
        return View(student);
   }

   [HttpPost]
   public async Task<IActionResult> Delete([FromForm]int id)
   {
        var student = await _context.Students.FindAsync(id);
        if(student == null)
        {
            return NotFound();
        }
        _context.Students.Remove(student);
        await _context.SaveChangesAsync();
        return RedirectToAction("Index");
   }

}

Views/Course/Create.cshtml
@model Course 

<h2>Course Add</h2>
<hr>
<form asp-controller="Course" asp-action="Create" method="post">
    <div class="mb-3">
        <label asp-for="CourseTitle" class="form-label">Course Title</label>
        <input asp-for="CourseTitle" class="form-control">
    </div>
   
    <button type="submit" class="btn btn-secondary">Save</button>

</form>

Views/Course/Delete.cshtml
@model Course

<p>
     do you want to delete the course named <b>@Model.CourseName</b>?

     <form asp-action="Delete" method="post">
        <input type="hidden" value="@Model.CourseId" name="id">
        <button class="btn btn-danger" type="submit">Yes</button>
        <a class="btn btn-primary" asp-action="Index">No</a>
     </form>
</p>

Views/Course/Edit.cshtml
@model Course 

<h2>Course Edit</h2>
<hr>
<div class="row">
    <div class="col-8">
        <form asp-controller="Course" asp-action="Edit" method="post">
            <input type="hidden" asp-for="CourseId">
            <div class="mb-3">
                <label asp-for="CourseName" class="form-label">Course Name</label>
                <input asp-for="CourseName" class="form-control">
            </div>
            <div class="mb-3">
                <label asp-for="CourseDescription" class="form-label">Course Description</label>
                <input asp-for="CourseDescription" class="form-control">
            </div>
            <button type="submit" class="btn btn-secondary">Save</button>
        </form>
    </div>

    <div class="col-4">
        <h4>Students</h4>
        <ul>
            @foreach(var item in Model.CourseRegistrations){
                <li>@item.Student.StudentName @item.Student.StudentSurname</li>
            }
        </ul>
    </div>

</div>

Views/Course/Index.cshtml
@model IEnumerable<Course>

<h2>Course List</h2>
<a asp-conroller="Course" asp-action="Create" class="btn btn-sm btn-success">Registration Course</a>
<hr>
<table class="table table-bordered">
    <thead class="thead-dark">
        <tr>
            <th>@Html.DisplayNameFor(model => model.CourseId)</th>
            <th>@Html.DisplayNameFor(model => model.CourseName)</th>
            <th>@Html.DisplayNameFor(model => model.CourseDescription)</th>
            <th style="width: 150px;"></th>
        </tr>
    </thead>
    <tbody>
        @foreach(var course in Model){
            <tr>
                <td>@Html.DisplayFor(model => course.CourseId)</td>
                <td>@Html.DisplayFor(model => course.CourseName)</td>
                <td>@Html.DisplayFor(model => course.CourseDescription)</td>
                <td>
                    <a asp-action="Edit" asp-route-id="@course.CourseId" class="btn btn-sm btn-primary">Edit</a>
                    <a asp-action="Delete" asp-route-id="@course.CourseId" class="btn btn-sm btn-danger">Delete</a>
                </td>
                
            </tr>
        }
    </tbody>
</table>

Views/CourseRegister/Create.cshtml
@model CourseRegistration 

<h2>Course Registration</h2>
<hr>
<form asp-controller="CourseRegister" asp-action="Create" method="post">
    <div class="mb-3">
        <label asp-for="StudentId" class="form-label">Student</label>
        <select asp-for="StudentId" asp-items = "ViewBag.Students" class="form-control">
            <option value="">Select</option>
        </select>
    </div>
    <div class="mb-3">
        <label asp-for="CourseId" class="form-label">Course</label>
        <select asp-for="CourseId" asp-items = "ViewBag.Courses" class="form-control">
            <option value="">Select</option>
        </select>
    </div>
   

    <button type="submit" class="btn btn-secondary">Save</button>

</form>

Views/CourseRegister/Index.cshtml
@model IEnumerable<CourseRegistration>

<h1>Course Registration</h1>
<table class="table table-bordered">
    <thead>
        <tr>
            <th style="width: 150px;">@Html.DisplayNameFor(m => m.CourseRegistrationId)</th>
            <th>@Html.DisplayNameFor(m => m.Student.StudentName) </th>
            <th>@Html.DisplayNameFor(m => m.Course.CourseName)</th>
            <th style="width: 150px;"></th>
        </tr>
    </thead>
    <tbody>
        @foreach(var item in Model){
            <tr>
                <td>@Html.DisplayFor(m => item.CourseRegistrationId)</td>
                <td>@Html.DisplayFor(m => item.Student.StudentName)</td>
                <td>@Html.DisplayFor(m => item.Course.CourseName)</td>
                <td>
                    <a asp-action="Edit" asp-route-id="@item.StudentId" class="btn btn-sm btn-primary">Edit</a>
                    <a asp-action="Delete" asp-route-id="@item.StudentId" class="btn btn-sm btn-danger">Delete</a>
                </td>
            </tr>
        }
    </tbody>
</table>

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - EfCoreApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/EfCoreApp.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">EfCoreApp</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Student" asp-action="Index">Student List</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Course" asp-action="Index">Course List</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="CourseRegister" asp-action="Index">Course Registrations</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - EfCoreApp - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Views/Student/Create.cshtml
@model Student 

<h2>Student Add</h2>
<hr>
<form asp-controller="Student" asp-action="Create" method="post">
    <div class="mb-3">
        <label asp-for="StudentName" class="form-label">Student Name</label>
        <input asp-for="StudentName" class="form-control">
    </div>
    <div class="mb-3">
        <label asp-for="StudentSurname" class="form-label">Student Surname</label>
        <input asp-for="StudentSurname" class="form-control">
    </div>
    <div class="mb-3">
        <label asp-for="StudentEmail" class="form-label">Email</label>
        <input asp-for="StudentEmail" class="form-control">
    </div>
    <div class="mb-3">
        <label asp-for="StudentPhone" class="form-label">Phone</label>
        <input asp-for="StudentPhone" class="form-control">
    </div>

    <button type="submit" class="btn btn-secondary">Save</button>

</form>

Views/Student/Delete.cshtml
@model Student

<p>
     do you want to delete the user named <b>@Model.StudentName</b>?

     <form asp-action="Delete" method="post">
        <input type="hidden" value="@Model.StudentId" name="id">
        <button class="btn btn-danger" type="submit">Yes</button>
        <a class="btn btn-primary" asp-action="Index">No</a>
     </form>
</p>

Views/Student/Edit.cshtml
@model Student 

<h2>Student Edit</h2>
<div class="row">
    <div class="col-8">
        <form asp-controller="Student" asp-action="Edit" method="post">
            <input type="hidden" asp-for="StudentId">
            <div class="mb-3">
                <label asp-for="StudentName" class="form-label">Student Name</label>
                <input asp-for="StudentName" class="form-control">
            </div>
            <div class="mb-3">
                <label asp-for="StudentSurname" class="form-label">Student Surname</label>
                <input asp-for="StudentSurname" class="form-control">
            </div>
            <div class="mb-3">
                <label asp-for="StudentEmail" class="form-label">Email</label>
                <input asp-for="StudentEmail" class="form-control">
            </div>
            <div class="mb-3">
                <label asp-for="StudentPhone" class="form-label">Phone</label>
                <input asp-for="StudentPhone" class="form-control">
            </div>
            
            <button type="submit" class="btn btn-secondary">Save</button>
        </form>
    </div>
    <div class="col-4">
        <h4>Courses</h4>
        <hr>
        <ul>
            @foreach(var item in Model.CourseRegistrations){
                <li>@item.Course.CourseName</li>
            }
        </ul>
    </div>
</div>

Views/Student/Index.cshtml
@model IEnumerable<Student>

<h2>Student List</h2>
<a asp-conroller="Student" asp-action="Create" class="btn btn-sm btn-success">Registration Student</a>
<hr>
<table class="table table-bordered">
    <thead class="thead-dark">
        <tr>
            <th>@Html.DisplayNameFor(model => model.StudentId)</th>
            <th>@Html.DisplayNameFor(model => model.StudentName)</th>
            <th>@Html.DisplayNameFor(model => model.StudentSurname)</th>
            <th style="width: 150px;"></th>
        </tr>
    </thead>
    <tbody>
        @foreach(var student in Model){
            <tr>
                <td>@Html.DisplayFor(model => student.StudentId)</td>
                <td>@Html.DisplayFor(model => student.StudentName)</td>
                <td>@Html.DisplayFor(model => student.StudentSurname)</td>
                <td>
                    <a  asp-action="Edit" asp-route-id="@student.StudentId" class="btn btn-sm btn-primary">Edit</a>
                    <a  asp-action="Delete" asp-route-id="@student.StudentId" class="btn btn-sm btn-danger">Delete</a>
                </td>
                
            </tr>
        }
    </tbody>
</table>